[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m venv /opt/venv && /opt/venv/bin/pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "/opt/venv/bin/alembic upgrade head && /opt/venv/bin/uvicorn api.main:app --host 0.0.0.0 --port $PORT"
