"""Initial schema

Revision ID: 0a38415c03f7
Revises: 
Create Date: 2026-03-21 20:25:02.292974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a38415c03f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('category_path', sa.Text(), nullable=True),
    sa.Column('weight_value', sa.Float(), nullable=True),
    sa.Column('weight_unit', sa.String(length=10), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('store_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('sku_id', sa.String(length=200), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('slug', sa.String(length=500), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('category_path', sa.Text(), nullable=True),
    sa.Column('top_category', sa.String(length=200), nullable=True),
    sa.Column('measurement_unit', sa.String(length=20), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'external_id', name='uq_store_external_id')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('list_price', sa.Float(), nullable=True),
    sa.Column('promo_price', sa.Float(), nullable=True),
    sa.Column('promo_description', sa.Text(), nullable=True),
    sa.Column('has_discount', sa.Boolean(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_product_id'], ['store_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('store_product_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_method', sa.String(length=20), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_product_id'], ['store_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'store_product_id', name='uq_product_store_match')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_matches')
    op.drop_table('prices')
    op.drop_table('store_products')
    op.drop_table('stores')
    op.drop_table('products')
    # ### end Alembic commands ###
