"""add Branch model and branch_id/content_hash to StoreProduct

Revision ID: 6982e47db2fb
Revises: 7e08522f6c78
Create Date: 2026-03-27 10:28:19.139347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6982e47db2fb'
down_revision: Union[str, Sequence[str], None] = '7e08522f6c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('external_store_id', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'external_store_id', name='uq_branch_store_external')
    )
    op.add_column('store_products', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('store_products', sa.Column('content_hash', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'store_products', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store_products', type_='foreignkey')
    op.drop_column('store_products', 'content_hash')
    op.drop_column('store_products', 'branch_id')
    op.drop_table('branches')
    # ### end Alembic commands ###
