"""Sync schema with latest branch and update models

Revision ID: 7a721793eba9
Revises: 6982e47db2fb
Create Date: 2026-03-27 15:47:43.547602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a721793eba9'
down_revision: Union[str, Sequence[str], None] = '6982e47db2fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('branches', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column('branches', sa.Column('address', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'branches', 'locations', ['location_id'], ['id'])
    op.add_column('prices', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prices', 'branches', ['branch_id'], ['id'])
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('store_products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_products', 'updated_at')
    op.drop_column('products', 'updated_at')
    op.drop_constraint(None, 'prices', type_='foreignkey')
    op.drop_column('prices', 'branch_id')
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.drop_column('branches', 'address')
    op.drop_column('branches', 'location_id')
    op.drop_table('locations')
    # ### end Alembic commands ###
