"""add savings_amount discount_percent to prices

Revision ID: 7e08522f6c78
Revises: 0a38415c03f7
Create Date: 2026-03-21 21:19:18.884904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e08522f6c78'
down_revision: Union[str, Sequence[str], None] = '0a38415c03f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('savings_amount', sa.Float(), nullable=True))
    op.add_column('prices', sa.Column('discount_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'discount_percent')
    op.drop_column('prices', 'savings_amount')
    # ### end Alembic commands ###
