"""add_blockedip_and_indices

Revision ID: 92cb1e57bc6c
Revises: 7a721793eba9
Create Date: 2026-04-08 22:08:07.321911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92cb1e57bc6c'
down_revision: Union[str, Sequence[str], None] = '7a721793eba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_ips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('blocked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    op.create_index(op.f('ix_prices_scraped_at'), 'prices', ['scraped_at'], unique=False)
    op.create_index(op.f('ix_products_canonical_name'), 'products', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_store_products_brand'), 'store_products', ['brand'], unique=False)
    op.create_index(op.f('ix_store_products_external_id'), 'store_products', ['external_id'], unique=False)
    op.create_index(op.f('ix_store_products_name'), 'store_products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_products_name'), table_name='store_products')
    op.drop_index(op.f('ix_store_products_external_id'), table_name='store_products')
    op.drop_index(op.f('ix_store_products_brand'), table_name='store_products')
    op.drop_index(op.f('ix_products_canonical_name'), table_name='products')
    op.drop_index(op.f('ix_prices_scraped_at'), table_name='prices')
    op.drop_table('blocked_ips')
    # ### end Alembic commands ###
